print ("Hello World!")
print ("What is your name")
iam=input()
print ("Ït is good to meet you, "+ iam)
print ("Length of your name is: ")
print (len(iam))
print ('What is your age?')
myage=input()
print ('You will be '+str(int(myage)+1)+' in a year' )